export { default as LoginScreen } from './LoginScreen';
export { default as DetailScreen } from './DetailScreen';
export { default as HomeScreen } from './HomeScreen';
export { default as MenuScreen } from './MenuScreen';
export { default as KirimanMenginap } from './KirimanMenginap';
export { default as ProduksiKiriman } from './ProduksiKiriman';
// export { default as TableProduksiKiriman } from './TableProduksiKiriman';
export { default as JatuhTempo } from './JatuhTempo';
// export { default as Irregulaity } from './Irregulaity';
export { default as UpdatesView } from './UpdatesView';
export { default as Profile } from './Profile';